### ISSUE TITLE
Домашно 2,задача 2

### ISSUE THREAD

**Issue by karinakozarova** [elsys/c-programming-homework#147]
До коя цифра след запетаята трябва да ни е закръглен output-а?

**Comment by wencakisa** [comment]
Според мен, щом не е указано в условието, значи не трябва да се закръгля.

**Comment by bankin** [comment]
Числото трябва да остане както е въведено (очевидно, ако са въведени повече цифри отколкото може да побере типа, някои от тях ще отпадната (ще бъдат неверни)), но за момента няма да тестваме с такива числа
