### ISSUE TITLE
5/20 tochki?

### ISSUE THREAD

**Issue by kocetomad** [elsys/c-programming-homework#294]
Ne razbiram kakvu problem imam sus 2,3,4 (kompilirani sa bez warningi i rabotyat).

**Comment by bankin** [comment]
клас и номер

**Comment by kocetomad** [comment]
v/03

**Comment by bankin** [comment]
Така е - работят. Четете си внимателно условията и си оправете програмите. Имате 5 точки, докато Генади не каже 20
