### ISSUE TITLE
Какъв е проблема с 2 зад ...

### ISSUE THREAD

**Issue by LazarFrenekev** [elsys/c-programming-homework#295]
При мен си се компилира и работи безгрешно ;(   ...

**Comment by bankin** [comment]
клас и номер

**Comment by LazarFrenekev** [comment]
16 г

**Comment by bankin** [comment]
Проблема е в моя компютър. Прави проблеми заради главната буква **.C** . Моля прекръстете си файла, защото ако аз го напрявя ще трябва да синхронизирате с репозиторито и ще стане по-сложно
