### ISSUE TITLE
Може ли да се използва европейско записване на дати?

### ISSUE THREAD

**Issue by Loosper** [elsys/c-programming-homework#378]
Крайният срок за домашното е написан във формат 2016.10.17, което е объркващо. Може ли да бъде 17.10.2016?

**Comment by bankin** [comment]
Кое е объркващото? И какво значение има?

**Comment by VitoNaychev** [comment]
Boyane ti si gospod. Vinagi se griji6 za udobstvoto na drugite. Respekt!!! :pray::pray::pray: :clap::clap::clap: :raised_hands::raised_hands::raised_hands: :punch::punch::punch: PROGRAMMING POWER  :punch::punch::punch:

**Comment by Loosper** [comment]
Според мен е по-четливо и по-ясно ако деня е преди месеца. Понякога ми се случва да ги объркам ако не са, ако погледна първата цифра без да се интересувам от месеца.

**Comment by bankin** [comment]
Хубавото на изписването на датите във формата година-месец-ден е, че се подреждат нещата много лесно, винаги са хронологично и затова за нас е предпочитан формат въпреки, че е вътре в текста. При изписване във формата ден-месец-година накрая получавате всички най-малки дни при сортиране и разбъркани месеци и години. (Американсия формат месец-ден-година е откровено гаден и дори не е на масата за обсъждане). Ако има повече хора, които желаят да сменим формата и го намират за объркващо - ще го сменим, но за момента ще го запазим в текущия вид :)

**Comment by Loosper** [comment]
Имах предвид само в readme - то, но благодаря

**Comment by Loosper** [comment]
Имах предвид само в readme - то, но благодаря
