### ISSUE TITLE
Оценяване

### ISSUE THREAD

**Issue by StefchoG** [elsys/c-programming-homework#622]
Добър вечер!
При предаването на домашно 02 преди два дни получих 15/20 точки (Warning-и на Task02.c). Редактирах файла и изпратих ново repository около два часа преди крайния срок, но не изписва задачата отново да е проверена и точките отново са 15. Възможно ли е да бъде оценена сега дори с 0.7 от максималния брой точки?
Благодаря ви!

**Comment by L3K0V** [comment]
А линк към pull-request и/или README.md дали ще може?
Ако го отвориш pull-request с оправените неща, би трябвало @elsysbot да ти ги преоцени.

**Comment by StefchoG** [comment]
Този линк ли имате впредвид : https://github.com/elsys/c-programming-homework/tree/master/A/02/25

**Comment by L3K0V** [comment]
Правим така: Ще ти добавя точките в HQ. 
Когато си пуснеш pull-request с оправената задача, **САМО** тя ще ти бъде оценена `* 0.7` :)

Успех
