### ISSUE TITLE
№16 G

### ISSUE THREAD

**Issue by LazarFrenekev** [elsys/c-programming-homework#653]
Какъв е проблема на 2ра зад. ?

**Comment by VitoNaychev** [comment]
При дефинирането на променливата "i" я направи равна на 0 иначе ще получаваш случайно(под случайно разбирай мястото което променливата ще вземе в рамта ти) число от рамта ти което е с големина 4 байта.

**Comment by rumendo** [comment]
Good guy naycho

**Comment by LazarFrenekev** [comment]
Много благодаря

**Comment by kocetomad** [comment]
kakav МЪЖ

**Comment by DanyYanev** [comment]
zatvori issue-to we
