### ISSUE TITLE
проблем с точките

### ISSUE THREAD

**Issue by DanielRusinov** [elsys/c-programming-homework#853]
защо всички които са пратили домашното на 26-ти имат по 14 точки в HQ като срокът беше до 26-ти включително?

**Comment by L3K0V** [comment]
Защото @elsysbot си мислеше, че срокът е до 25 включително.
Можеш ли да ми пуснеш тук списък с хората, да ги гледам довечера?

**Comment by DanielRusinov** [comment]
От нашия клас са 1,3,6,11,20,23,26
https://docs.google.com/spreadsheets/d/1eLAm7mQ0s5NvEYH8Y3w9btwD8kcAjiHOJRZvGVJBe8s/edit#gid=524817967

**Comment by MagiMarinova** [comment]
От А клас са 2,5,10,11,14,18,20,22,23,25,26 , а домашното на 17 все още не е мърджнато
https://docs.google.com/spreadsheets/d/1eLAm7mQ0s5NvEYH8Y3w9btwD8kcAjiHOJRZvGVJBe8s/edit#gid=524817967
