### ISSUE TITLE
Бота е счупен!

### ISSUE THREAD

**Issue by Gazzy16** [elsys/c-programming-homework#858]
Не ми проберява домашното което съм пуснал на време, а проверява на някой, който е закъснял с предаването!

**Comment by Gazzy16** [comment]
Valve plz fix.

**Comment by L3K0V** [comment]
Отговорих ти в #829. Ще го гледаме. Ама няма как бота да бачка за 100 човека, пък за теб персонално да е счупен :D Нещо ти си го счупил
